[templates.rust]
path = "./rust"
description = "Typical Rust project template"
welcome = """
# Bleur stack simple Rust & Nix template

## Intended usage
The intended usage of this flake is to write a project on Rust which compiles to an executable project

## Important
Please, after bootstrapping your own project, don't forget to read readme.md for more infomration on usage.

## More info
- [Rust language](https://rust-lang.org)
- [Rust NixOS Wiki](https://nixos.wiki/wiki/Rust)
"""

[templates.rust-nightly]
path = "./rust-nightly"
description = "Nightly Rust project template using fenix"
welcome = """
# Bleur stack nightly Rust & Nix template

## Intended usage
The intended usage of this flake is to write a project on nightly version of Rust toolchain which compiles to an executable project

## Important
Please, after bootstrapping your own project, don't forget to read readme.md for more infomration on usage.

## More info
- [Fenix for Nix](https://github.com/nix-community/fenix)
- [Rust language](https://rust-lang.org)
- [Rust NixOS Wiki](https://nixos.wiki/wiki/Rust)
"""

[templates.rust-shared]
path = "./rust-shared"
description = "C shared/static library with libc on Rust template"
welcome = """
# Bleur stack C shared/static library with libc on Rust & Nix template

## Intended usage
The intended usage of this flake is to write a C static/shared library with libc on Rust

## Important
Please, after bootstrapping your own project, don't forget to read readme.md for more infomration on usage.

## More info
- [Libc-rs](https://docs.rs/libc/latest/libc/)
- [Fenix for Nix](https://github.com/nix-community/fenix)
- [Rust language](https://rust-lang.org)
- [Rust NixOS Wiki](https://nixos.wiki/wiki/Rust)
"""

[templates.rust-actix]
path = "./rust-actix"
description = "Rust + Actix template with Diesel and Nix"
welcome = """
# Bleur stack actix & postgresql server on Rust & Nix template with NixOS modules
## Intended usage
The intended usage of this flake is to write a backend server application on Rust/Actix and deploy it on NixOS server

## Important
Please, after bootstrapping your own project, don't forget to read readme.md for more infomration on usage.

## More info
- [Actix.rs](https://actix.rs)
- [Diesel.rs](https://diesel.rs)
- [Rust language](https://rust-lang.org)
- [Rust NixOS Wiki](https://nixos.wiki/wiki/Rust)
"""

[templates.rust-actix-docker]
path = "./rust-actix-docker"
description = "Rust + Actix template with Diesel and Docker"
welcome = """
# Bleur stack Rust + Actix service with Docker

## Intended usage
The intended usage of this template is to build a Rust web service using Actix
and run it in a containerized environment for local development and production.

## Important
After bootstrapping your project, make sure to read `readme.md`
for details on project structure, environment variables, and Docker workflows.

## More info
- Actix Web: https://actix.rs
- Diesel: https://diesel.rs
- Rust language: https://www.rust-lang.org
- Docker: https://www.docker.com
"""

[templates.rust-telegram]
path = "./rust-telegram"
description = "Rust + Nix template for Telegram-bots"
welcome = """
# Bleur stack telegram bot on Rust & Nix with NixOS modules template
## Intended usage
The intended usage of this flake is to write a Telegram bot on Rust and deploy it on NixOS server

## Important
Please, after bootstrapping your own project, don't forget to read readme.md for more infomration on usage.

## More info
- [Teloxide](https://github.com/teloxide/teloxide/)
- [Rust language](https://rust-lang.org)
- [Rust NixOS Wiki](https://nixos.wiki/wiki/Rust)
"""

[templates.ts-react]
path = "./ts-react"
description = "React + TypeScript template with Vite and Nix"
welcome = """
# Bleur stack React + TypeScript template
#
## Intended usage
The intended usage of this template is to quickly bootstrap React applications with TypeScript, Vite (Rolldown), and a reproducible Nix development environment.

## Important
Please, after bootstrapping your own project, don't forget to read README.md for more information on usage and available commands.

## More info
- [React Documentation](https://react.dev)
- [Vite Documentation](https://vitejs.dev)
- [TypeScript Handbook](https://www.typescriptlang.org/docs/)
- [Nix Flakes](https://nixos.wiki/wiki/Flakes)
"""
