[templates.rust]
path = "./rust"
description = "Typical Rust project template"
welcome = """
# Bleur stack simple Rust & Nix template

## Intended usage
The intended usage of this flake is to write a project on Rust which compiles to an executable project

## Important
Please, after bootstrapping your own project, don't forget to read readme.md for more infomration on usage.

## More info
- [Rust language](https://rust-lang.org)
- [Rust NixOS Wiki](https://nixos.wiki/wiki/Rust)
"""

[templates.rust-nightly]
path = "./rust-nightly"
description = "Nightly Rust project template using fenix"
welcome = """
# Bleur stack nightly Rust & Nix template

## Intended usage
The intended usage of this flake is to write a project on nightly version of Rust toolchain which compiles to an executable project

## Important
Please, after bootstrapping your own project, don't forget to read readme.md for more infomration on usage.

## More info
- [Fenix for Nix](https://github.com/nix-community/fenix)
- [Rust language](https://rust-lang.org)
- [Rust NixOS Wiki](https://nixos.wiki/wiki/Rust)
"""

[templates.rust-shared]
path = "./rust-shared"
description = "C shared/static library with libc on Rust template"
welcome = """
# Bleur stack C shared/static library with libc on Rust & Nix template

## Intended usage
The intended usage of this flake is to write a C static/shared library with libc on Rust

## Important
Please, after bootstrapping your own project, don't forget to read readme.md for more infomration on usage.

## More info
- [Libc-rs](https://docs.rs/libc/latest/libc/)
- [Fenix for Nix](https://github.com/nix-community/fenix)
- [Rust language](https://rust-lang.org)
- [Rust NixOS Wiki](https://nixos.wiki/wiki/Rust)
"""

[templates.ts-react]
path = "./ts-react"
description = "React + TypeScript template with Vite and Nix"
welcome = """
# Bleur stack React + TypeScript template
#
## Intended usage
The intended usage of this template is to quickly bootstrap React applications with TypeScript, Vite (Rolldown), and a reproducible Nix development environment.

## Important
Please, after bootstrapping your own project, don't forget to read README.md for more information on usage and available commands.

## More info
- [React Documentation](https://react.dev)
- [Vite Documentation](https://vitejs.dev)
- [TypeScript Handbook](https://www.typescriptlang.org/docs/)
- [Nix Flakes](https://nixos.wiki/wiki/Flakes)
"""
