[project]
name = "rust"

## Variables

[[variable]]
variable = "name"
default = "project"
message = "What would you like to name this project?"

[[variable]]
variable = "version"
default = "0.1.0"
message = "What would be initial version?"

[[variable]]
placeholder = "website"
default = "https://bleur.net"
message = "Is there any website hosted for this project?"

[[variable]]
placeholder = "#repository#"
default = "https://github.com/bleur-org/templates"
message = "What's the link to the repo?"

[[variable]]
placeholder = "#description#"
default = "My very awesome rust project"
source = "Cargo.toml"
message = "What's this project about generally?"

[[variable]]
variable = "author"
default = "Bleur Developers"
message = "Who's going to be author?"

[[change]]
placeholder = "#name#"
source = "Cargo.toml"
value = "@name@"

[[change]]
placeholder = "#version#"
source = "Cargo.toml"
value = "@version@"

[[change]]
placeholder = "#website#"
source = "Cargo.toml"
value = "@website@"

[[change]]
placeholder = "#website#"
source = "Cargo.toml"
value = "@website@"

[[change]]
placeholder = "#author#"
source = "Cargo.toml"
value = "@author@"
